/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MapaPreciosRouteImport } from './routes/mapa-precios'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultadoIdRouteImport } from './routes/resultado.$id'

const MapaPreciosRoute = MapaPreciosRouteImport.update({
  id: '/mapa-precios',
  path: '/mapa-precios',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultadoIdRoute = ResultadoIdRouteImport.update({
  id: '/resultado/$id',
  path: '/resultado/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mapa-precios': typeof MapaPreciosRoute
  '/resultado/$id': typeof ResultadoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mapa-precios': typeof MapaPreciosRoute
  '/resultado/$id': typeof ResultadoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mapa-precios': typeof MapaPreciosRoute
  '/resultado/$id': typeof ResultadoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mapa-precios' | '/resultado/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mapa-precios' | '/resultado/$id'
  id: '__root__' | '/' | '/mapa-precios' | '/resultado/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MapaPreciosRoute: typeof MapaPreciosRoute
  ResultadoIdRoute: typeof ResultadoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mapa-precios': {
      id: '/mapa-precios'
      path: '/mapa-precios'
      fullPath: '/mapa-precios'
      preLoaderRoute: typeof MapaPreciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultado/$id': {
      id: '/resultado/$id'
      path: '/resultado/$id'
      fullPath: '/resultado/$id'
      preLoaderRoute: typeof ResultadoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MapaPreciosRoute: MapaPreciosRoute,
  ResultadoIdRoute: ResultadoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
